kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Release.Name }}
  # name: israeldaskal-hello-world
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your lab user name
        # app: israeldaskal-hello-world
        app: {{ .Release.Name }}
    spec:
      volumes:
          - name: index-html
            configMap:
              name: index.html
              defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          # update with the image you build in part 1
<<<<<<< HEAD
          image: '{{ .Values.containers.image }}:{{ .Values.containers.tag }}'
=======
          image: '{{ .Values.containers.image }}:{{ .Values.containers.tag }}' 
>>>>>>> 16f1f34bdb30b991538f79ef300caff5db6f3b5a
          volumeMounts:
          - name: index-html
            mountPath: /tmp/html # this will mount the html.index file to it application location
          # image: 'quay.io/israeldaskal/argocd:v2'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
