ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/israeldaskal/argocd'
  tag: 'chart_v1'

service:
  servicePort: 8080

readinessProbe:
  httpGet:
    path: '/health/readiness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

livenessProbe:
  httpGet:
    path: '/health/readiness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volumes:
  mount:
    path: '/tmp/html'
